# Generated by Django 4.0.2 on 2022-02-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(max_length=64)),
                ('wrong', models.CharField(max_length=64)),
            ],
        ),
    ]
