# Generated by Django 4.0.2 on 2022-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightwrong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='numOfAttempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='numOfCorrect',
            field=models.IntegerField(default=0),
        ),
    ]
