# Generated by Django 4.0.2 on 2022-02-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightwrong', '0003_word_lastattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='lastAttempt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
