# Generated by Django 4.0.2 on 2022-02-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rightwrong', '0004_alter_word_lastattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='lastAttempt',
        ),
    ]
