# Generated by Django 4.0.2 on 2022-03-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightwrong', '0007_word_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pronunciation',
            field=models.FileField(null=True, upload_to='pronunciation/'),
        ),
    ]
