# Generated by Django 4.0.2 on 2022-03-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightwrong', '0008_word_pronunciation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='pronunciation',
        ),
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
